core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views

urlpatterns = [
    path('', include('allauth.urls')), # AllAuth Required NB. Not default of 'accounts/'
    path('', include('your_app.urls')),
    path('edit_user_details/', views.edit_user_details, name='edit_user_details'),
    path('admin/', admin.site.urls),
]

your_app/urls.py
"""Defines URL patterns for your_app app"""

from django.urls import path

from . import views

app_name = 'your_app'
urlpatterns = [
    # Home Page
    path('', views.index, name='index'),
    # Home Page again with optional parm, I don't believe in esoteric code (regex)
    path('<slug:option>', views.index, name='index'),
]

your_app/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm

class EditProfileForm(ModelForm):

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name'
        )

core/views.py
from django.shortcuts import render #    get_object_or_404, redirect, 
from django.contrib.auth.decorators import login_required
from core.forms import EditProfileForm
from django.contrib import messages
# from django.urls import is_valid_path
# from django.contrib.auth.forms import UserChangeForm

# Create your views here.

@login_required
def edit_user_details(request):
    """A page for the user to view and update their details."""
    # user = get_object_or_404(user, id=request.user)

    page_title = 'Name'

    if request.method != 'POST':
        form = EditProfileForm(instance=request.user)
        message = ''
    else:
        form = EditProfileForm(instance=request.user, data=request.POST)

        if form.is_valid():
            form.save()
            message = 'Details saved'

    messages.success(request, message )

    context = {'user': request.user, 'message': message, 'form': form, 'page_title': page_title }

    return render(request, "edit_user_details.html", context )

your_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request, option='Home'):
    """The home page for Your Site"""
    page_title = option

    if option == 'Option3':
        long_content = "Page filler for testing fixed navbar." * 80
    else:
        long_content = ""

    context = {
        'page_title': page_title,
        'long_content': long_content,
    }
    return render(request, "index.html", context )

core/templates/base.html
<!doctype html>

{% load bootstrap4 %}

{% load static %}

<link rel="stylesheet" href="{% static 'core/style.css' %}"/>
<html lang="en"/>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport"
          content="width=device-width, initial-scale-1, shrink-to-fit=no"/>
    {% if page_title %}
        <title>Your App: {{ page_title }}</title>
    {% else %}
        <title>Your App:
            {% block head_title %}{% endblock head_title %}
        </title>
    {% endif %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <!-- Bootstrap CDN -->
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous"/>
    {% comment %}
        <!-- FontAwesome CDN -->
        <link rel="stylesheet"
              href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
              integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay"
              crossorigin="anonymous">
    {% endcomment %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="screen"/>
    <!-- Jquery CDN - must come before Select 2 usage -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <!-- Select 2 CNDs -->
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
          rel="stylesheet"/>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body class="body_for_fixed_nav">
    <button onclick="topFunction()" id="myBtn" title="Go to top">Top</button>
    <script>
        //Get the button
        var mybutton = document.getElementById("myBtn");

        // When the user scrolls down 20px from the top of the document, show the button
        window.onscroll = function () { scrollFunction() };

        function scrollFunction() {
            if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
                mybutton.style.display = "block";
            } else {
                mybutton.style.display = "none";
            }
        }

        // When the user clicks on the button, scroll to the top of the document
        function topFunction() {
            document.body.scrollTop = 0;
            document.documentElement.scrollTop = 0;
        }
    </script>
    <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'your_app:index' 'Home' %}">Home</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <!-- View functions -->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'your_app:index' 'Option1' %}">Option1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'your_app:index' 'Option2' %}">Option2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'your_app:index' 'Option3' %}">Option3</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"
                           href="{% url 'your_app:index' 'Registered_Option4' %}">Registered Option4</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    {% if request.user.is_staff %}
                        {% comment %} Responsive padding 'Mobile First' {% endcomment %}
                        <li class="nav-item pl-0 pl-sm-3 pt-3 pt-sm-0">
                            <a class="nav-link" href="{% url 'your_app:index' 'Staff_Option' %}">Staff Option1</a>
                        </li>
                    {% endif %}
                    <li class="nav-item pl-0 pl-sm-3 pt-3 pt-sm-0">
                        <div class="nav-link dropdown">
                            <a class="dropdown-toggle"
                               href="#"
                               role="button"
                               id="dropdownMenuLink"
                               data-toggle="dropdown"
                               aria-haspopup="true"
                               aria-expanded="false">
                                {% if user.first_name %}
                                    {{ user.first_name }}
                                {% else %}
                                    {{ user.username }}
                                {% endif %}
                                - profile
                            </a>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'account_logout' %}">Sign out</a>
                                <a class="dropdown-item" href="{% url 'edit_user_details' %}">Name</a>
                                <a class="dropdown-item" href="{% url 'account_email' %}">Emails</a>
                                <a class="dropdown-item" href="{% url 'account_change_password' %}">Password</a>
                            </div>
                        </div>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% bootstrap_messages %}
    <main role="main" class="container">
        <div>
            {% block page_header %}
            {% endblock page_header %}
        </div>
        <div class="mb-3">
            {% block content %}
            {% endblock content %}
        </div>
        <div class="pb-2 mb-2 border-top">
            {% block footer %}
                <center>
                    <a href="{% url 'your_app:index' 'About' %}">About</a> -
                    <a href="{% url 'your_app:index' 'Change_Log' %}">Change log</a>
                </center>
                {% if request.user.is_staff %}
                    <center>
                        <a href="./admin" target="blank">admin</a> -
                        <a href="https://github.com/ClearSky0?tab=repositories" target="blank">github</a>
                        <br/>
                    </center>
                {% endif %}
            {% endblock footer %}
        </div>
    </main>
</body>

core/templates/edit_user_details.html
{% extends "account/account_base.html" %}

{% load bootstrap4 %}

{% block content_well %}
  <h1>Update Name</h1>
    <form action="{% url 'edit_user_details' %}" method="post" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">Update</button>
      {% endbuttons %}
    </form>
{% endblock content_well %}

your_app/templates/index.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% load static %}

{% block page_header %}
<div class="jumbotron">
    <center>
        <h1 class="dislplay-3"><b>Y</b>our <b>A</b>pp</h1>

        <p class="lead">What is your site about?</p>
        <p class="lead">Who is your audience?</p>
        <p><b>{{ page_title }}</b></p>

        {% if not user.is_authenticated %}
        <div>
            <a class="btn btn-primary" href="{% url 'account_login' %}" role="button">Log in &raquo;</a>

            <a class="btn btn-primary" href="{% url 'account_signup' %}" role="button">Register &raquo;</a>
        </div>
        {% else %}

            <a class="btn btn-primary" href="{% url 'your_app:index' 'Option1' %}" role="button">Option1 &raquo;</a>

        {% endif %}

        <div style="border-style:solid; border-radius: 15pt;max-width: 100%;margin: 30pt;padding: 10pt"><a
                href="https://www.bloomberg.com/news/articles/2022-03-18/world-s-happiest-ranking-goes-to-finland-for-fifth-year-in-a-row"
                target="blank">“The lesson of the World Happiness Report over the years is that social support,
                generosity to one another, and <b>honesty in government</b> are crucial for well-being,” Jeffrey Sachs,
                director of the Center for Sustainable Development at Columbia University.</a>
        </div>

        <h1>{{ long_content }}</h1>

    </center>
</div>
{% endblock page_header %}
{% block content %}
{% endblock content %}